cache: apt
sudo: false
language: python
python:
  - "2.7"
  - "3.4"
addons:
  apt:
    packages:
    - libatlas-dev
    - libatlas-base-dev
    - liblapack-dev
    - gfortran
before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
install:
  - conda install --yes python=$TRAVIS_PYTHON_VERSION pip numpy scipy pandas
  - pip install pytest-pep8 pytest-cov python-coveralls
  - python setup.py develop
script:
  - THEANO_FLAGS=floatX=float32 py.test -v --pep8 --cov=downhill --cov-report=term-missing
after_success:
  - coveralls
