language: clojure
sudo: true
before_install: # bc is apparently not provided by default
   - sudo apt-get install bc
install:
   - cd daemon
   - lein deps
   - cd ../client
   - lein deps
   - cd ..
script: test/integration.sh
jdk:
  - openjdk7
  - oraclejdk7
  - oraclejdk8
