dist: xenial
language: d

d:
  - dmd
  - ldc-beta
  - ldc

os:
  - linux
# TODO, some bug in OSX for the server that causes it to fail
#  - osx

env:
  - BUILD=
  - BUILD=dub LIBDPARSE_VERSION=min
  - BUILD=dub LIBDPARSE_VERSION=max
  - BUILD=dub DSYMBOL_VERSION=min
  - BUILD=dub DSYMBOL_VERSION=max

branches:
  only:
  - master
  - /^v\d+\.\d+\.\d+([+-]\S*)*$/

script: ./.travis.sh
jobs:
  include:
    - stage: GitHub Release
      #if: tag IS present
      d: ldc-1.23.0
      os: linux
      script: echo "Deploying to GitHub releases ..." && ./release.sh
      deploy:
        provider: releases
        api_key: $GH_REPO_TOKEN
        file_glob: true
        file: bin/dcd-*.tar.gz
        skip_cleanup: true
        on:
          repo: dlang-community/DCD
          tags: true
    - stage: GitHub Release
      #if: tag IS present
      d: ldc-1.23.0
      os: osx
      script: echo "Deploying to GitHub releases ..." && ./release.sh
      deploy:
        provider: releases
        api_key: $GH_REPO_TOKEN
        file_glob: true
        file: bin/dcd-*.tar.gz
        skip_cleanup: true
        on:
          repo: dlang-community/DCD
          tags: true
    - stage: GitHub Release
      #if: tag IS present
      d: ldc-1.23.0
      os: linux
      script: echo "Deploying to GitHub releases ..." && ./release-windows.sh
      addons:
        apt:
          packages:
            - p7zip-full
        deploy:
          provider: releases
          api_key: $GH_REPO_TOKEN
          file_glob: true
          file: bin/dcd-*.zip
          skip_cleanup: true
          on:
            repo: dlang-community/DCD
            tags: true
    - stage: GitHub Release
      #if: tag IS present
      d: ldc-1.23.0
      os: linux
      script: echo "Deploying to GitHub releases ..." && ARCH=64 ./release-windows.sh
      addons:
        apt:
          packages:
            - p7zip-full
        deploy:
          provider: releases
          api_key: $GH_REPO_TOKEN
          file_glob: true
          file: bin/dcd-*.zip
          skip_cleanup: true
          on:
            repo: dlang-community/DCD
            tags: true
stages:
  - name: test
    if: type = pull_request or (type = push and branch = master)
