language: java
jdk:
  - openjdk8

services:
  - xvfb

before_install:
  - "export DISPLAY=:99.0"

after_success:
  - mvn test cobertura:cobertura coveralls:report

addons:
  # workaround for openjdk buffer overflow https://github.com/travis-ci/travis-ci/issues/5227
  hostname: dummy
