application: iogrowcrm
version: 22
runtime: python27
api_version: 1
threadsafe: true

inbound_services:
- mail
libraries:
- name: jinja2
  version: latest
- name: endpoints
  version: latest
- name: ssl
  version: latest

builtins:
- remote_api: on
- appstats: on

handlers:
- url: /admin/.*
  script: google.appengine.ext.admin.application
  login: admin
- url: /static
  static_dir: static

- url: /bower_components
  static_dir: bower_components

- url: /static/landing
  static_dir: static/landing
  expiration: "30d"

# Endpoints handler
- url: /_ah/spi/.*
  script: crm.services.application

- url: /_ah/mail/.+
  script: handle_incoming_email.app
  login: admin
- url: /.*
  script: crm.handlers.app


skip_files:
- ^node_modules$
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^\.idea$
- ^\.git$
- ^(.*/)?.*\.pot?$
- ^(.*/)?.*\.dist-info$
- ^(.*/)?.*\.md$
- ^(.*/)?.*\.rst$
- ^(.*/)?.*\.datastore$
