language: rust
sudo: false

rust:
  - stable
  - beta
  - nightly

os:
  - linux
  - osx

env:
  - CARGO_FEATURES='--features default'
  - CARGO_FEATURES='--no-default-features'

# necessary for `travis-cargo coveralls --no-sudo`
addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev

cache:
  directories:
    - $HOME/.cargo

matrix:
  allow_failures:
    - rust: nightly
  exclude:
    - os: osx
      env: CARGO_FEATURES='--no-default-features'

before_script:
  - pip install 'travis-cargo<0.2' --user && export PATH=`python -m site --user-base`/bin:$PATH

script:
  - travis-cargo build -- $CARGO_FEATURES
  - travis-cargo test -- $CARGO_FEATURES
  - rustdoc --test README.md -L target/debug -L target/debug/deps
  - cargo doc --no-deps

after_success:
  - if [ "$TRAVIS_OS_NAME" == 'linux' ]; then
      travis-cargo coveralls --no-sudo;
    fi

notifications:
  email:
    on_success: never
