language: go
go:
  - 1.5

sudo: required

env:
- GO15VENDOREXPERIMENT=1

cache:
  apt: true
  directories:
    - $HOME/librtlsdr

addons:
  apt:
    packages:
    - libusb-1.0-0-dev

before_install:
  - bash install-rtlsdr.sh